Repository kubeflow/xgboost-operator, pull requests merged in 2019-05, with the labels that each got.

#3 project setup
  .gitignore
  Gopkg.lock
  Gopkg.toml
  hack/boilerplate/boilerplate.go.txt
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/xgboost/v1alpha1/constants.go
  pkg/apis/xgboost/v1alpha1/defaults.go
  pkg/apis/xgboost/v1alpha1/doc.go
  pkg/apis/xgboost/v1alpha1/register.go
  pkg/apis/xgboost/v1alpha1/types.go
  pkg/apis/xgboost/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/xgboost/v1alpha1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/fake_xgboost_client.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/fake_xgboostjob.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/xgboost_client.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/xgboostjob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/xgboost/interface.go
  pkg/client/informers/externalversions/xgboost/v1alpha1/interface.go
  pkg/client/informers/externalversions/xgboost/v1alpha1/xgboostjob.go
  pkg/client/listers/xgboost/v1alpha1/expansion_generated.go
  pkg/client/listers/xgboost/v1alpha1/xgboostjob.go
  pkg/controller.v1alpha1/xgboost/controller.go
Labels: approved, lgtm, size/XXL

#5 Fix comment TFReplicaSpec -> ReplicaSpec
  pkg/apis/xgboost/v1alpha1/constants.go
Labels: approved, lgtm, size/XS

#6 boilerplate codes of (XGBoost)Controller
  .gitignore
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  LICENSE
  OWNERS
  README.md
  cmd/xgboost-operator.v1alpha1/app/options/options.go
  cmd/xgboost-operator.v1alpha1/app/server.go
  cmd/xgboost-operator.v1alpha1/main.go
  go.mod
  go.sum
  hack/boilerplate/boilerplate.go.txt
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/xgboost/v1alpha1/constants.go
  pkg/apis/xgboost/v1alpha1/defaults.go
  pkg/apis/xgboost/v1alpha1/doc.go
  pkg/apis/xgboost/v1alpha1/register.go
  pkg/apis/xgboost/v1alpha1/types.go
  pkg/apis/xgboost/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/xgboost/v1alpha1/zz_generated.defaults.go
  pkg/apis/xgboost/validation/validation.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/fake_xgboost_client.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/fake/fake_xgboostjob.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/xgboost_client.go
  pkg/client/clientset/versioned/typed/xgboost/v1alpha1/xgboostjob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/xgboost/interface.go
  pkg/client/informers/externalversions/xgboost/v1alpha1/interface.go
  pkg/client/informers/externalversions/xgboost/v1alpha1/xgboostjob.go
  pkg/client/listers/xgboost/v1alpha1/expansion_generated.go
  pkg/client/listers/xgboost/v1alpha1/xgboostjob.go
  pkg/common/util/v1alpha1/unstructured/informer.go
  pkg/controller.v1alpha1/xgboost/controller.go
  pkg/controller.v1alpha1/xgboost/informer.go
  pkg/controller.v1alpha1/xgboost/job.go
  pkg/controller.v1alpha1/xgboost/pod.go
  pkg/controller.v1alpha1/xgboost/status.go
  pkg/version/version.go
Labels: approved, lgtm, size/XXL

#11 Added badges and link to XGBoost
  README.md
Labels: approved, lgtm, size/XS

#17 Add goveralls task on Travis
  .travis.yml
Labels: approved, lgtm, size/XS

#19 Remove cover.out
  .gitignore
  cover.out
Labels: size/XS

#20 Fix OWNERS file permission
  OWNERS
Labels: size/XS
