Repository kubeflow/xgboost-operator, pull requests merged in 2020-05, with the labels that each got.

#50 For the worker rank, we should add the offset caused by the master re…
  go.mod
  pkg/controller/xgboostjob/pod.go
  pkg/controller/xgboostjob/pod_test.go
  pkg/controller/xgboostjob/xgboostjob_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#51 Add initial list of adopters
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#52 Update Dockerfile
  config/samples/smoke-dist/Dockerfile
  config/samples/smoke-dist/requirements.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#53 Fix typo of comment in apis.go
  pkg/apis/apis.go
Labels: approved, lgtm, ok-to-test, size/XS

#59 Add a easy install instruction in readme
  README.md
  manifests/xgboost-operator/base/cluster-role-binding.yaml
Labels: approved, lgtm, ok-to-test, size/M

#63 add docker images to README
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#68 Skip create/delete logs for unrelated pods
  README.md
  pkg/controller/xgboostjob/expectation.go
  pkg/controller/xgboostjob/xgboostjob_controller.go
Labels: approved, lgtm, size/M

#70 Set timeout for cloud build and upgrade goland version
  Dockerfile
  build_image.sh
Labels: approved, lgtm, size/XS

#69 Bump k8s and controller runtime version
  go.mod
  go.sum
  pkg/controller/xgboostjob/pod.go
  pkg/controller/xgboostjob/service.go
  pkg/controller/xgboostjob/xgboostjob_controller.go
Labels: approved, lgtm, size/XL

#74 Remove redundant copy of manifests and update installation instructions
  README.md
  manifests/xgboost-operator/base/cluster-role-binding.yaml
  manifests/xgboost-operator/base/cluster-role.yaml
  manifests/xgboost-operator/base/crd.yaml
  manifests/xgboost-operator/base/deployment.yaml
  manifests/xgboost-operator/base/kustomization.yaml
  manifests/xgboost-operator/base/params.env
  manifests/xgboost-operator/base/params.yaml
  manifests/xgboost-operator/base/service-account.yaml
  manifests/xgboost-operator/base/service.yaml
  manifests/xgboost-operator/overlays/application/application.yaml
  manifests/xgboost-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, size/L

#79 Set different expectation keys for pod and service
  pkg/controller/xgboostjob/expectation.go
Labels: approved, lgtm, size/S

#80 Add a necessary installation step to README
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#82 Add v1 controller/APIs and support multi-version
  cmd/manager/main.go
  pkg/apis/addtoscheme_xgboostjob.go
  pkg/apis/xgboostjob/v1/constants.go
  pkg/apis/xgboostjob/v1/doc.go
  pkg/apis/xgboostjob/v1/register.go
  pkg/apis/xgboostjob/v1/v1_suite_test.go.back
  pkg/apis/xgboostjob/v1/xgboostjob_types.go
  pkg/apis/xgboostjob/v1/xgboostjob_types_test.go.back
  pkg/apis/xgboostjob/v1/zz_generated.deepcopy.go
  pkg/controller/v1/add_xgboostjob.go
  pkg/controller/v1/controller.go
  pkg/controller/v1/xgboostjob/expectation.go
  pkg/controller/v1/xgboostjob/job.go
  pkg/controller/v1/xgboostjob/pod.go
  pkg/controller/v1/xgboostjob/pod_test.go
  pkg/controller/v1/xgboostjob/service.go
  pkg/controller/v1/xgboostjob/util.go
  pkg/controller/v1/xgboostjob/xgboostjob_controller.go
  pkg/controller/v1/xgboostjob/xgboostjob_controller_suite_test.go.back
  pkg/controller/v1/xgboostjob/xgboostjob_controller_test.go.back
  pkg/controller/v1alpha1/add_xgboostjob.go
  pkg/controller/v1alpha1/controller.go
  pkg/controller/v1alpha1/xgboostjob/expectation.go
  pkg/controller/v1alpha1/xgboostjob/job.go
  pkg/controller/v1alpha1/xgboostjob/pod.go
  pkg/controller/v1alpha1/xgboostjob/pod_test.go
  pkg/controller/v1alpha1/xgboostjob/service.go
  pkg/controller/v1alpha1/xgboostjob/util.go
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller.go
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller_suite_test.go.back
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller_test.go.back
Labels: approved, lgtm, size/XXL

#84 Remove v1alpha1 apis and controller codes
  pkg/apis/addtoscheme_xgboostjob.go
  pkg/apis/xgboostjob/v1alpha1/constants.go
  pkg/apis/xgboostjob/v1alpha1/doc.go
  pkg/apis/xgboostjob/v1alpha1/register.go
  pkg/apis/xgboostjob/v1alpha1/v1alpha1_suite_test.go.back
  pkg/apis/xgboostjob/v1alpha1/xgboostjob_types.go
  pkg/apis/xgboostjob/v1alpha1/xgboostjob_types_test.go.back
  pkg/apis/xgboostjob/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/v1alpha1/add_xgboostjob.go
  pkg/controller/v1alpha1/controller.go
  pkg/controller/v1alpha1/xgboostjob/expectation.go
  pkg/controller/v1alpha1/xgboostjob/job.go
  pkg/controller/v1alpha1/xgboostjob/pod.go
  pkg/controller/v1alpha1/xgboostjob/pod_test.go
  pkg/controller/v1alpha1/xgboostjob/service.go
  pkg/controller/v1alpha1/xgboostjob/util.go
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller.go
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller_suite_test.go.back
  pkg/controller/v1alpha1/xgboostjob/xgboostjob_controller_test.go.back
Labels: approved, lgtm, size/XXL

#85 Migrate v1 implementation to latest kubeflow/common
  go.mod
  go.sum
  pkg/apis/xgboostjob/v1/xgboostjob_types.go
  pkg/apis/xgboostjob/v1/zz_generated.deepcopy.go
  pkg/controller/v1/xgboostjob/expectation.go
  pkg/controller/v1/xgboostjob/job.go
  pkg/controller/v1/xgboostjob/pod.go
  pkg/controller/v1/xgboostjob/pod_test.go
  pkg/controller/v1/xgboostjob/service.go
  pkg/controller/v1/xgboostjob/util.go
  pkg/controller/v1/xgboostjob/xgboostjob_controller.go
Labels: approved, lgtm, size/L
