Repository kubeflow/xgboost-operator, pull requests merged in 2020-04, with the labels that each got.

#46 Fix the link to run_e2e_workflow.py script
  prow_config.yaml
Labels: approved, lgtm, size/XS

#47 Update to latest version of kubeflow/common
  go.sum
Labels: approved, lgtm, size/XS

#48 Remove Gopkg.lock and Gopkg.toml files
  Gopkg.lock
  Gopkg.toml
  go.sum
Labels: lgtm, size/XXL

#49 Update dockerfile
  config/samples/xgboost-dist/Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/XS
