Repository kubeflow/xgboost-operator, pull requests merged in 2021-03, with the labels that each got.

#110 XGBoost Operator: Move manifests development upstream
  README.md
  go.mod
  go.sum
  manifests/xgboost-operator/base/cluster-role-binding.yaml
  manifests/xgboost-operator/base/cluster-role.yaml
  manifests/xgboost-operator/base/crd.yaml
  manifests/xgboost-operator/base/deployment.yaml
  manifests/xgboost-operator/base/kustomization.yaml
  manifests/xgboost-operator/base/params.env
  manifests/xgboost-operator/base/service-account.yaml
  manifests/xgboost-operator/base/service.yaml
  manifests/xgboost-operator/overlays/application/application.yaml
  manifests/xgboost-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, size/XL

#112 Fixes #111: wrong variable scope
  pkg/controller/v1/xgboostjob/xgboostjob_controller.go
Labels: approved, lgtm, size/XS

#113 Fix typos in xgboostjob_types comment
  pkg/apis/xgboostjob/v1/xgboostjob_types.go
Labels: approved, lgtm, size/XS

#114 XGBoost Operator: Refactor manifests structure
  README.md
  manifests/base/cluster-role-binding.yaml
  manifests/base/cluster-role.yaml
  manifests/base/crd.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/service-account.yaml
  manifests/base/service.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/xgboost-operator/overlays/application/application.yaml
Labels: approved, lgtm, size/M

#116 Change to use v1 crd in manifest
  config/crds/xgboostjob_v1_xgboostjobs.yaml
  config/samples/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
  manifests/base/crd.yaml
  manifests/base/kustomization.yaml
Labels: approved, lgtm, size/XXL

#118 Add v1 samples and README.md
  README.md
  config/samples/smoke-dist/xgboostjob_v1_rabit_test.yaml
  config/samples/xgboost-dist/xgboostjob_v1_iris_predict.yaml
  config/samples/xgboost-dist/xgboostjob_v1_iris_train.yaml
Labels: approved, lgtm, size/L
